### ISSUE TITLE
Lazy Load Suggestion

### ISSUE THREAD

**Issue by tessguefen** [caleboleary/jQuery-Extended-Mag#5]
On Load of image, show image, instead of loading image while user waits for it to load.
While loading, give user an area for "text" or and "image" for "Loading..." which will only show up when you're activating the zoom (or allow it to be shown before the zoom is activated)
By zoom activated i mean hovering the image.

**Comment by caleboleary** [comment]
Addressed here https://github.com/caleboleary/jQuery-Extended-Mag/commit/2a22e9e41ad58c2954bab4de5a7fa36968a984d6

Thanks!
